### ISSUE TITLE
20231010版的传输问题

### ISSUE THREAD

**Issue by egg1234** [cnbatch/kcptube#10]
首先20231010版在一份服务器配置文件，一个kcptube客户端站点情况下，播放4k视频没有问题，使用的是issue 8的配置

有问题的场景是一份服务器配置文件，两个同城运营商的异地客户端站点同时连接这台的服务器（即分别两个站点linux客户端，服务器还是只有一份配置），两个站点同时播放4k视频就卡顿，同样使用的是issue 8的配置，而且已经分别尝试使用fast1/fast3/fast5，情况一样

但是回退使用20231002版就完全没有问题，与上面一样的是一份服务器配置文件，两个同城运营商的异地客户端站点同时连接这台的服务器（两个站点linux客户端就是上面使用的两台，服务器还是同样这份配置不变），两个站点同时播放4k视频完全不会出现卡顿问题，同样使用的是issue 8的配置，使用fast5，至少证明kcptube是可以同时支持多客户端没有传输性能问题的

**Comment by cnbatch** [comment]
新发布的版本顺便解决了这个问题，可以一并试试
