### ISSUE TITLE
[feature request]能否也考虑支持远程端口转发（或者叫反向端口转发）

### ISSUE THREAD

**Issue by egg1234** [cnbatch/kcptube#12]
相对于本地端口转发（或者叫正向端口转发），远程端口转发这个功能一般是由ssh -R命令实现的，或者如gost的rtcp://:10122/127.0.0.1:22命令参数实现

应用场景是远端的服务器在内网，只能出局连接公网，没有端口映射权限，而客户端的机器有公网地址或能够进行端口映射，然后客户端机器作为kcptube的服务端，而远端服务器反而作为kcptube的客户端连接到客户端机器

如果这时kcptube有远程端口转发功能的话，可以把服务器的端口如22/21/23等转发（或映射）给客户端机器的一个自定义端口，这时用户连接到客户端机器的这些自定义端口就等于直接连接到了服务器的相应端口

主要是考虑kcptube作为一个优秀的流量转发工具，更全面的流量转发功能也是更多用户使用的动力

谢谢！

**Comment by cnbatch** [comment]
如果真的有这种需求，更好的做法有两种：
1. 开一个新的配置文件，本机指定为 server 模式，对端为 client 模式。如果本机无公网IP，那么可以配合 stun_server 选项打洞。
2. kcptube 通道内使用 WireGuard 或 OpenVPN，或任意类型的 VPN。这样就可以配合路由表随便转发。

这是因为我从一开始就不打算做这样的功能，但考虑到有时候确实需要反过来传输，并且本机未必有公网 IP，所以才会有 stun_server 的选项。虽然这个选项反倒在 [UDPHop](https://github.com/cnbatch/udphop) 用得比较多。
开启该选项后，会把打洞后的 IP 与端口写入到 log_path 内的 ip_address.txt 文件，所以可以考虑做个定时任务，把这个文件隔一段时间就上传至网盘，方便出门在外时查看。

不打算做远程监听转发至本机的原因很简单，比如像这样
```mermaid
graph LR;
    A[Client A]-- config1 -->S[Server];
    B[Client B] -- config1 -->S[Server];
```
若两个客户端都采用相同的配置文件，会造成 Server 侧端口冲突，出现两个选择困难：
1. 服务器无法二次绑定，向客户端报错
2. 不再重新绑定，但会导致服务器不知道应该转发给谁

万一客户端崩溃或意外断线（比如运行在路由器，掉电重启了），服务器肯定是来不及释放的。等到客户端重启完成建立了新的连接，那么服务器侧同样会遇到上述的选择困难。像这种情况，第二种选择显然更合适，但判断起来十分麻烦。
简单粗暴选择第一种的话，那就要等到原先断掉的链路超时了才能释放端口。

既然处理过程那么麻烦，那就索性支持 STUN 打洞功能，适应性会更广阔。而且支持 STUN 打洞一点都不麻烦，比起“远程端口转发至本地”简单很多。
从目前的情况来看，除了像 ZeroTier 以及 [frp](https://github.com/fatedier/frp) 之类的内网穿透工具，我还没见过哪个转发软件自带 STUN 打洞功能。
