### ISSUE TITLE
建议为用户说明一下/etc/sysctl.conf文件参数的设置

### ISSUE THREAD

**Issue by egg1234** [cnbatch/kcptube#13]
因为/etc/sysctl.conf文件里面的net.core.rmem_max参数对于udp包传输的性能有比较关键的影响，

以hysteria协议为例，它原来的1.x项目里面有专门说明net.core.rmem_max参数值与带宽值的一些建议比例关系

另外xtaci/kcptun项目也有专门说明net.core.rmem_max参数的，当然它还提到了其他一些相关参数，不过就我自己测试来看，对udp传输性能影响最关键的还是net.core.rmem_max参数，估计这也是hysteria项目当时仅仅是建议了net.core.rmem_max参数值的原因

谢谢！

**Comment by cnbatch** [comment]
好的，README 文件已经添加说明
