### ISSUE TITLE
大容量文件下载随机中断的问题

### ISSUE THREAD

**Issue by egg1234** [cnbatch/kcptube#14]
问题场景，下载 http://mirror.uoregon.edu/ubuntu-releases/20.04.6/ 的iso桌面安装映像（4.1GB），vps位于俄勒冈州，在vps上测试wget下载这个俄勒冈州立大学的托管网站映像没有任何问题，但是vps通过kcptube（有端口跳跃）转发gost的socks5代理，在境内用firefox浏览器设置代理进行下载就会出现随机的中断的问题（无论是否晚高峰），为了对比同一台vps安装hysteria转发gost的socks5代理，在境内用firefox浏览器设置代理进行下载没有任何问题，顺利下载4.1GB的iso文件

为了防止俄勒冈州立大学的托管网站有特殊问题，另外也使用了 http://mirrors.vcea.wsu.edu/ubuntu-releases/20.04.6/ 华盛顿州立大学的托管网站，然后在华盛顿州再开了另外一台vps，在vps上测试wget下载这个华盛顿州立大学的托管网站的iso桌面安装映像（4.1GB）没有任何问题，但同样这台vps通过kcptube（有端口跳跃）转发gost的socks5代理，在境内用firefox浏览器设置代理进行下载也出现随机的中断的问题（无论是否晚高峰），为了对比同一台vps安装hysteria转发gost的socks5代理，在境内用firefox浏览器设置代理进行下载没有任何问题，也顺利下载4.1GB的iso文件

但奇怪的是这些vps的kcptube转发gost的socks5代理，在境内连续1个多小时播放4k视频却完全没有中断或卡顿（无论是否晚高峰），也是使用firefox浏览器设置socks5代理进行播放的，只有下载大容量文件才会随机出现中断，而且以上所有测试在晚高峰及白天的早上低峰时间段都做过，情况一样，应该和拥挤没有关系

谢谢！

**Comment by cnbatch** [comment]
正在用哪个配置？（fast还是regular）

以及丢包率、延迟的状况如何？这两个很关键

**Comment by cnbatch** [comment]
感谢反馈，排查后发现几个星期前优化原版 KCP 性能时，对数据包 ACK 的部份处理不当（几个星期前使用原版 KCP 的版本没这个 ACK 的问题）。这个部份现在已经修复好了。

另外需要注意的是，无论是原版KCP还是现在优化过的，主要目标仍然是降低延迟，而非传输大流量（README.md 开头就提到过）。其中 README.md 底部就提到过原版 issue 区的《如何避免缓存积累延迟的问题》，意思就是流量过大会缓存区爆满会导致延迟越来越大。再加上 kcptube 本身在 keep_alive 过期后（过期时间 = 内置过期阈值 31 秒 + 用户设置的 keep_alive 时长）仍收不到任何数据包时，会认为连接受阻、失效，于是就强制断开连接。所以丢包率越高的环境，就越容易因为等待时间过久而间接导致 kcptube 断线。

目前能够做的也就只有尽量缓解，比如使用更激进的 fast1 或 fast2，以及把 keep_alive 的时间延长一点。

更强力的缓解措施是内置 FEC 机制，不过这并非立即能够做得到，要改的地方很多，并不简单。
KCPTUN 和 UDPSpeeder 就内置了 FEC 机制，用的都是 Reed-Solomon 算法，然而 KCPTUN 只支持转发 TCP 数据包（有人提议加上 UDP，作者不愿做），UDPSpeeder 只转发 UDP 数据包。
他们的创作时间都比我早很多年，但都不做同时支持 TCP + UDP + FEC，所以短期内我应该也没什么好办法了。

**Comment by cnbatch** [comment]
kcp_resend 数值越小，就越激进。
kcp_resend 指的是 KCP 内部的 `fastresend` 变量值，表示跨越了指定次数后就不再等待，直接重传。
数值越大，等待时间就越长。

刚刚在 Wiki 页面增加了简单版的模式解读：
https://github.com/cnbatch/kcptube/wiki/%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8#%E6%A8%A1%E5%BC%8F%E8%A7%A3%E8%AF%BB%E7%AE%80%E6%98%93%E7%89%88
不但把列表中对应的原变量名都列了出来，也给出了简单说明，可以参考着选择

**Comment by cnbatch** [comment]
用的是浏览器还是curl？

如果需要下载文件，其实可以直接指向服务器的端口，无须再一次中转：
https://github.com/cnbatch/kcptube/wiki/%E6%9B%B4%E5%A4%9A%E5%85%B7%E4%BD%93%E7%A4%BA%E4%BE%8B
按照这里的做法，对于高延迟高丢包的线路，curl会在10秒左右的时候见到速度稍微下降（可能会降为0），随后速率再次上升，如此波动一两次之后，传输率会稳定下来。

加个 `blast=1` 效果更好。

对于浏览器，既然都已经用着socks5了，在当前连接传文件或许会更简便。

**Comment by cnbatch** [comment]
从170ms延迟到330ms延迟的线路都试了下，在开启mux_tunnels的时候，fast3和fast4及往后比较容易出现这种情况，fast1和fast2很难出现

我试验的方式：
```mermaid
graph LR;
    A[Python3 HTTP Server]-->B[kcptube Server];
    B-->C[kcptube Client];
    C-->D[curl];
```

```mermaid
graph LR;
    A[Target Website]-->B[SS Server];
    B-->C[kcptube Server];
    C-->D[kcptube Client];
    D-->E[SS Client];
    E-->F[Browser];
```

即使是达到10%的丢包率，fast1~fast2模式都试不出断流的情况，速度降为0倒是出现过很多次，一般两秒左右后就恢复了。

fast3~fast4在这种丢包率+300ms高延迟的情况下，会有几率出现断流。往后的配置，几率会更高。如果碰到连续丢包，那就很容易断。

对于TCP连接而言（无mux_tunnels），能够造成连接断掉的情况只有3种：
1. 外部TCP主动断开
2. TCP超时（这是操作系统协议栈的事情）
3. keep alive 检测包超时

任一情况成立都会断开

对于mux_tunnels，能够造成断连的情况只有2种：
1. keep alive 检测包超时
2. 当前 KCP 连接超过31秒收不到任何数据

同样，任一情况成立都会断开

其中，keep alive超时断开，会主动告知对端。检测到超时的既可以是server侧，也可以是client侧。目前的流程是：
```mermaid
graph LR;
    A[kcptube Local] -- keep_alive -->B[kcptube Peer];
    B-- keep_alive_response-->A;
```
所以，如果这中间阻塞太严重，是会导致连接断开的。
以前的做法只是单向发送，于是对面程序崩溃了自己仍然不知道，最后改成现在这样。

对于keep alive的情况，稍微灵活点的方案是，我把断连判断改成“keep alive检测包超时”且“当前 KCP 连接超过31秒收不到任何数据“同时成立才算作真正的keep alive超时，可以有所缓解。

至于浏览器看视频不会断，原因是浏览器从多台服务器获取数据时并不会只走单条mux tunnel（除非mux_tunnels数值低到只有1或2），而是分布于多条tunnel，那就没那么容易造成阻塞。

**Comment by cnbatch** [comment]
这个 bug 终于找到了，不启用 mux_tunnels，在高延迟(300ms+)、超高丢包率(30%)的情况下，下载大量小文件（小于1M）时多次复现。

原因是 Server 模式立即关闭连接导致的，这时候还有少量数据来不及传回客户端。新版本修复了这个 bug。

虽然 mux_tunnels 未发现有这种情况，但从流量图表发现速率经常大起大落。起因是 mux_tunnels 模式自身的缓存数据转移至 KCP 缓存时的方式如同中小学数学题“一边排水一边灌水”，满了就停，有余量就放。两层缓存都这样。因为每次“排放”的数据量的差别可以很大，于是 TCP 的流控也会被弄得大起大落。现在新版本改成了“KCP 缓存完全排空才能接数据”的方式，表现相对稳定多了。

**Comment by wangyu-** [comment]
>KCPTUN 和 UDPSpeeder 就内置了 FEC 机制，用的都是 Reed-Solomon 算法，然而 KCPTUN 只支持转发 TCP 数据包（有人提议加上 UDP，作者不愿做），UDPSpeeder 只转发 UDP 数据包。
他们的创作时间都比我早很多年，但都不做同时支持 TCP + UDP + FEC，所以短期内我应该也没什么好办法了。

UDPspeeder wiki里面有一篇文章有讲，怎么kcptun和UDPspeeder并联，同时支持UDP和TCP。 U

DPspeeder不做tcp是因为强调不同软件配合，这样你对哪个功能不满意都可以换掉。 比如kcptun+udpspeeder+ss， 你可以换掉kcptun也可以换掉udpspeeder也可以换掉ss。  如果所有功能都做到一个软件里，没办法轻易替换掉其中的一部分，你只能求作者开发/改进。

**Comment by cnbatch** [comment]
这就十分奇怪了，会不会是gost的问题？
我用的是xray-core里面的shadowsocks，同时下载两个文件都不会断，v2ray的shadowsocks也试过，同样没断。

```mermaid
graph LR;
    A[KCPTube Client]<-->B[xray-core as shadowsocks client];
    B<-->C[xray-core as shadowsocks server];
    C<-->D[KCPTube Server];
```
