### ISSUE TITLE
Feature requests: probe / healthcheck

### ISSUE THREAD

**Issue by honwen** [cnbatch/kcptube#3]
有没有健康检查的方式？好做高可用/负载均衡

**Comment by cnbatch** [comment]
接下来的版本会完善 keep-alive 的用途，一旦超时（Keep-alive设置的秒数 + 30秒）就断开故障的通道，对后续新连接重新再建立新的通道。

用作客户端时也会在命令行提供 `--try` 选项，用于测试服务器能否连通。

**Comment by cnbatch** [comment]
刚刚发布的新版本解决了连接不稳定的问题
高延迟和丢包率忽高忽低的时候，尽量不要用 regular 4 ~ 5，以免 TCP 掉线

如果需要更高的吞吐量，可以在配置文件内加一个 `blast=1`，唯一缺点是CPU负载会变高，可能会导致嵌入式设备持续高热

**Comment by honwen** [comment]
稳定性验证非常OK

**Comment by honwen** [comment]
目前使用方式: 作为 SS 的 SIP003 插件

https://github.com/honwen/openwrt-kcptube-plugin
