### ISSUE TITLE
Cannot start docker 

### ISSUE THREAD

**Issue by bao3** [cnbatch/kcptube#4]
I started  the docker in the `Synolgy` Docker  and had mounted `configfiel.conf`, when I tried to start it , I got the `ERROR` :

```
Start container local-kcptube failed: {"message":"OCI runtime create failed: container_linux.go:367: starting container process caused: exec: \"/kcptube\": permission denied: unknown"}.
```

Then I tried start a new docker  container from ` Portainer ` but it's not so lucky , I got the same error .

**Comment by cnbatch** [comment]
刚刚重新打包了一份新的，这回应该可以了

上一份打包时忘了`chmod +x`，重新打包的就加了回去
前面有好几个旧版本也有同样的情况，那些就不改了，以新版为准

**Comment by bao3** [comment]
> 

感谢及时更新。我在几台设备间折腾了一夜，正准备收官睡觉，看到你这一条，我决定。。。再折腾一小时。
