### ISSUE TITLE
请教延迟的问题

### ISSUE THREAD

**Issue by bao3** [cnbatch/kcptube#5]
我自己的 2 台 vps，我平时使用多种方式与 vps 连接，这其中我使用 SSH 作为代理。但我搭建了 kcptube 后，发现延迟相关有点大，具体表现是：

我的vps 的 Ping 是 147～155ms ，比较恒定。
我通过 SSH 连接后，HTTP 的延迟是 310ms
但我通过 kcptube 之后，http 延迟是 700ms+
比如下面的截图

[Imgur](https://imgur.com/AcFgswf)

**Comment by cnbatch** [comment]
不太清楚这种面板的测试方式（我从未用过），而且由于不清楚图中这些SSH代理和kcptube的配置模式，我没办法评论。

我个人实测，在 fast4 模式下，kcptube 的延迟表现还是不差的。
这些都是我测试过的方案：

套一层 Shadowsocks:
```mermaid
graph LR;
    A["Browser"]
    B["Shadowsocks (Client)"]
    C["kcptube (Router)"]
    D["kcptube (VPS)"]
    E["Shadowsocks (Server)"]
    F["Target Website"]
    A <--> B <--> C <--> D <--> E <--> F
```

套一层  OpenVPN:
```mermaid
graph LR;
    A["OpenVPN (Client)"]
    B["kcptube (Router)"]
    C["kcptube (VPS)"]
    D["OpenVPN (Server)"]
    A <--> B <--> C <--> D
```

套一层  WireGuard:
```mermaid
graph LR;
    A["WireGuard (Client)"]
    B["kcptube (Router)"]
    C["kcptube (VPS)"]
    D["WireGuard (Server)"]
    A <--> B <--> C <--> D
```

在套了 OpenVPN 的情况下实测 ping：
![image](https://github.com/cnbatch/kcptube/assets/8210187/1f4b2659-ad15-4af0-ad5e-58a08df48c3f)

对比直连的 ping:
![image](https://github.com/cnbatch/kcptube/assets/8210187/042608e7-94d2-4a5c-b2eb-90f1f39ffac3)

**Comment by cnbatch** [comment]
这是套了 shadowsocks 后在 fast.com 的测试结果：
![image](https://github.com/cnbatch/kcptube/assets/8210187/139c1201-e88c-440f-b3b7-824336bae180)

**Comment by bao3** [comment]
感谢回复。我想，可能是我的 vps cpu 太差，跑 kcptube 时，cpu 引起了延迟。

发自我的iPad

**Comment by cnbatch** [comment]
忘了提及一个重要的选项：kcptube 客户端设置 mux_tunnels。
小提示：只须在客户端启用，服务器端的配置文件不认这个选项。

对于 shadowsocks 以及各种 socket 代理，包括 SSH Tunnel，都应该启用这个选项，比如设置成 `mux_tunnels=3`

在 wiki 的《更多具体示例》有提到（参考Shadowsocks部份）
https://github.com/cnbatch/kcptube/wiki/%E6%9B%B4%E5%A4%9A%E5%85%B7%E4%BD%93%E7%A4%BA%E4%BE%8B
更多细节可以参考项目首页的《多路复用》部份。

如果不启用该选项，那么每次有入站连接都会做一次“建立 KCP 连接”的处理，对于 TCP 连接而言，意味着需要握手两次（TCP一次，KCP一次）。这样会导致双倍等待时间。同时也消耗 CPU 资源，因为建立一次连接需要消耗两个 KCP 链路——第一个用于获取 ID 号码并获取链路 RTT 值，第二个用于正式通讯。

启用多路复用后，就会预先建立相应数量的 KCP 连接，后续每次 TCP 连接以及 UDP 连接都会从已存在的链路传输数据，无须新建 KCP 连接，也就无须多次重复握手，减少CPU消耗和等待的时间。
只不过该选项也并不是没有代价（尽管比较低）。为了平衡多条连接之间的发送需求，避免单条连接挤占其它连接的资源，程序内专门为此多加了一层缓存组，结果就是流量接近满载时，延迟会稍微增高。当然了，比起每次都握手，这个“代价”就可以忽略不计了。

Socket 类代理每接受一条入站连接，都会创建一条对应的出站新连接，不管是 TCP 还是 UDP 都这样。`mux_tunnels` 选项就是为此而设的。
VPN 程序则相反，只会创建固定数量的连接（通常只有一条）。这种情况就不需要使用 `mux_tunnels` 选项了。

其它转发软件，例如 KCPTUN，是强制启用MUX的。我不太喜欢强行启用MUX，于是就做成单独的选项。

**Comment by bao3** [comment]
实测 `mux_tunnels=4` 在我的网络环境下，可以有效降低延迟。感谢你的耐心解答。
