### ISSUE TITLE
About the MTU,using with wireguard

### ISSUE THREAD

**Issue by Handsome1080P** [cnbatch/kcptube#7]
My tunnel MTU set as defualt 1440.WG need set 1440-80=1360?

**Comment by cnbatch** [comment]
Just make sure that the MTU value of kcptube is smaller than the MTU value of the broadband. The MTU value of WireGuard can be set to any value.

If the purpose is to reduce waste, WireGuard's MTU can be set as:
* kcptube's MUX is not set
    * MTU - 24 (KCP Header) - 5 (kcptube's headers) = 1440 - 24 - 5 = 1411
* kcptube's MUX is enabled
    * MTU - 24 (KCP Header) - 9 (kcptube's headers) = 1440 - 24 - 9 = 1407

**Comment by Handsome1080P** [comment]
> 只需确保kcptube的MTU值小于宽带的MTU值即可。WireGuard 的 MTU 值可以设置为任意值。
> 
> 如果目的是减少浪费，WireGuard的MTU可以设置为：
> 
> * kcptube 的 MUX 未设置
>   
>   * MTU - 24（KCP 标头） - 5（kcptube 的标头）= 1440 - 24 - 5 = 1411
> * kcptube 的 MUX 已启用
>   
>   * MTU - 24（KCP 标头） - 9（kcptube 的标头）= 1440 - 24 - 9 = 1407

I see,thx
