### ISSUE TITLE
客户端报告错误“open: Too many open files”

### ISSUE THREAD

**Issue by egg1234** [cnbatch/kcptube#8]
kcptube-linux-glibc-x64.tar.xz
服务端及客户端操作系统都是ubuntu 20.04.6服务器版（非桌面版）

root用户启动
#./kcptube kcpclient.conf
客户端报告错误
kcptube version 20230924
Error Found in Configuration File(s): No
Servers: 0
Relays: 0
Clients: 1
start_up() running in client mode
[2023-09-25 11:11:11 +0000] open: Too many open files

如果是kcptube-linux-musl-x64.tar.bz2版
报告错误
open: No file descriptors available

系统open files数是缺省的，没有改变过
```# ulimit -a``` 
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3491
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 3491
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

下面是服务器的配置文件内容，服务器没有报错

mode=server
kcp=fast1
inbound_bandwidth=500M
outbound_bandwidth=500M
listen_port=11000-11999
destination_port=6000
destination_address=127.0.0.1
dport_refresh=20
encryption_password=password
encryption_algorithm=AES-GCM
keep_alive=10
ipv4_only=1

下面是客户端的配置文件内容

mode=client
kcp=fast1
inbound_bandwidth=450M
outbound_bandwidth=50M
listen_port=6000
destination_port=11000-11999
destination_address=www.mydomain.com
dport_refresh=20
encryption_password=password
encryption_algorithm=AES-GCM
keep_alive=10
ipv4_only=1
mux_tunnels=65535

上面的mux_tunnels=1020也一样的报错

请教一下应该怎样修改参数才能运行

谢谢！

**Comment by cnbatch** [comment]
这是因为不少 Linux 发行版的 Open Files 数量限制为 1024，所以很容易会遇到这种问题。

临时解决办法：
1. 运行命令 `ulimit -n`，查看输出的数值。这个数值几乎都是 1024。
2. 如果数值确实只有 1024，请运行命令 `ulimit -n 300000`


永久解决办法：
编辑 /etc/security/limits.conf，在末尾加上

```
*         hard    nofile       300000
*         soft    nofile       300000
root      hard    nofile       300000
root      soft    nofile       300000
```

**Comment by cnbatch** [comment]
mux_tunnels=500
这个设置有点多，先降到5~10试试，大多数情况下是够用的
