### ISSUE TITLE
[feature request]能否考虑在同一个客户端配置文件增加多个端口转发

### ISSUE THREAD

**Issue by egg1234** [cnbatch/kcptube#9]
如果大佬有精力，能否考虑在同一个客户端配置文件增加多个端口转发，类似下面的配置方式，而且这样也可以不需要在服务器定义转发目的地端口，全部由客户端配置文件决定

  "forward": {
    "127.0.0.1:12322": "127.0.0.1:22",
    "0.0.0.0:5201/tcp": "127.0.0.1:5201",
    "0.0.0.0:5353/udp": "8.8.8.8:53"
  }

或者

  "relay_tcps": [
    {
      "listen": "127.0.0.1:2222", // TCP 转发监听地址
      "remote": "123.123.123.123:22", // TCP 转发目标地址
      "timeout": 300 // TCP 超时秒数
    },
    {
      "listen": "127.0.0.1:13389", // TCP 转发监听地址
      "remote": "124.124.124.124:3389", // TCP 转发目标地址
      "timeout": 300 // TCP 超时秒数
    }
  ],
  "relay_udps": [
    {
      "listen": "127.0.0.1:5333", // UDP 转发监听地址
      "remote": "8.8.8.8:53", // UDP 转发目标地址
      "timeout": 60 // UDP 超时秒数
    },
    {
      "listen": "127.0.0.1:11080", // UDP 转发监听地址
      "remote": "9.9.9.9.9:1080", // UDP 转发目标地址
      "timeout": 60 // UDP 超时秒数
    }
  ],

谢谢！

**Comment by cnbatch** [comment]
新版本提供了这个功能，只不过并不使用json格式，具体用法在这里：[自定义映射模式 ](https://github.com/cnbatch/kcptube/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%98%A0%E5%B0%84%E6%A8%A1%E5%BC%8F)

超时秒数没办法单独设置，因为在 mux tunnel 模式下是统一管理的。如果专门为不使用 mux tunnel 的模式增加设置的话，那就会增加配置文件的复杂程度。所以“单独设置超时”就只能放弃了。

**Comment by cnbatch** [comment]
都是相互独立的
dport_refresh 的有效范围是客户端与服务器之间的连接路径，而 udp_timeout 是指 UDP 应用程序 ↔ kcptube 之间的超时设置
